git:
  depth: 3
  quiet: true
  submodules: false
language: go
go:
  - 1.14.x
  - 1.15.x
  - master
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
before_install:
  - nvm install node
install:
  - make install
script:
  - make web
  - make rcoredump
  - make rcoredumpd
  - make test
